# Generated by Django 5.1.1 on 2024-09-20 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_conversation'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='message_by_user',
            field=models.BooleanField(default=True),
        ),
    ]
